### PR TITLE
GH-71 - Table Styling

### PR DESCRIPTION
**Pull request by auniverseaway**
* Add basic borders to tables (color scheme aware)
* Add default margin to table to center
* Add border collapse
* Add very basic paragraph margins

Resolves: GH-71

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by auniverseaway** [comment]
# Before
Screen Shot 2022-03-10 at 6 42 20 PM

# After
Screen Shot 2022-03-10 at 6 43 15 PM

**Comment by LucaNerlich** [comment]
the package.lock change does not seem right.

**Comment by auniverseaway** [comment]
@LucaNerlich Typically you always commit package-lock updates.

**Comment by auniverseaway** [comment]
Closing. Can revisit later.

**Pull request closed without merging**
